### ISSUE TITLE
求论文

### ISSUE THREAD

**Issue by bulletmzh** [gao-ouyang/demo_for_kalmanFilter#2]
您好，仓库里的论文已经失效，希望能够学习一下，可以发一份到我的邮箱吗，谢谢。 2291104330@qq.com

**Comment by gao-ouyang** [comment]
我刚刚试了，可以下载的， 你再试试

**Comment by bulletmzh** [comment]
谢谢，刚试了下，下载好了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gao-ouyang/demo_for_kalmanFilter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 中午11:43
收件人:&nbsp;"gao-ouyang/demo_for_kalmanFilter"<demo_for_kalmanFilter@noreply.github.com&gt;;
抄送:&nbsp;"SilverBullet"<2291104330@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gao-ouyang/demo_for_kalmanFilter] 求论文 (#2)





 
我刚刚试了，可以下载的， 你再试试
